export const SOCKET = 'SOCKET';
export const UNREADMSG = 'UNREADMSG'
export const INCUNREADMSG = 'INCUNREADMSG'
export const DECUNREADMSG = 'DECUNREADMSG'
export const SETTOZERO = 'SETTOZERO'
export const SINGLEUNREADMSG = 'SINGLEUNREADMSG'
export const ARRIVALMESSAGE = 'ARRIVALMESSAGE'